language: ruby
cache: bundler
dist: trusty
sudo: false
addons:
  chrome: stable
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem update --system
  - gem update
services:
  - postgresql
