language: ruby
cache: bundler
dist: trusty
sudo: false
notifications:
  email: false
addons:
  chrome: beta
  apt:
    packages:
      - libzbar-dev
before_install:
  - gem update --system
  - gem install bundler
  - gem update
  - createuser -U postgres bookmooch
  - createdb -U postgres -O bookmooch bookmooch_test
