language: ruby
cache: bundler
dist: trusty
sudo: required
notifications:
  email: false
services:
  - postgresql
addons:
  chrome: stable
  postgresql: "9.6"
  apt:
    packages:
      - libzbar-dev
      - google-chrome-stable
before_install:
  - rvm get head
  - gem update --system
  - gem install bundler
  - gem update
  - createuser -U postgres bookmooch
  - createdb -U postgres -O bookmooch bookmooch_test
script:
  - bundle exec ruby spec/spec.rb
