language: ruby
cache: bundler
dist: precise
sudo: required
addons:
  chrome: stable
  apt:
    packages:
      - libzbar-dev
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - gem update --system
  - gem install bundler
  - gem update
