language: ruby
cache: bundler
dist: trusty
sudo: false

notifications:
  email: false
services:
  - postgresql
addons:
  chrome: beta
  postgresql: "9.6"
  apt:
    packages:
      - libzbar-dev
before_install:
  - rvm get head
  - gem update --system
  - gem install bundler
  - gem update
  - createuser -U postgres bookmooch
  - createdb -U postgres -O bookmooch bookmooch_test
script:
  - ruby spec/spec.rb
